//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryInfoDatabaseLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectoryInfoDatabaseLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY
        ///{
        ///	BACKGROUND-COLOR: white;
        ///	FONT-FAMILY: &quot;Verdana&quot;, sans-serif;
        ///	FONT-SIZE: 100%;
        ///	MARGIN-LEFT: 0px;
        ///	MARGIN-TOP: 0px
        ///}
        ///P
        ///{
        ///	FONT-FAMILY: &quot;Verdana&quot;, sans-serif;
        ///	FONT-SIZE: 70%;
        ///	LINE-HEIGHT: 12pt;
        ///	MARGIN-BOTTOM: 0px;
        ///	MARGIN-LEFT: 10px;
        ///	MARGIN-TOP: 10px
        ///}
        ///.note
        ///{
        ///	BACKGROUND-COLOR: white;
        ///	COLOR: #336699;
        ///	FONT-FAMILY: &quot;Verdana&quot;, sans-serif;
        ///	FONT-SIZE: 100%;
        ///	MARGIN-BOTTOM: 0px;
        ///	MARGIN-LEFT: 0px;
        ///	MARGIN-TOP: 0px;
        ///	PADDING-RIGHT: 10px
        ///}
        ///.infotable
        ///{
        ///	BACKGROUND-COLOR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiffReport {
            get {
                return ResourceManager.GetString("DiffReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiffReport_Minus {
            get {
                object obj = ResourceManager.GetObject("DiffReport_Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiffReport_Plus {
            get {
                object obj = ResourceManager.GetObject("DiffReport_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:msxsl=&apos;urn:schemas-microsoft-com:xslt&apos;&gt;
        ///
        ///    &lt;xsl:template match=&quot;##XML_ELEMENT_DIRECTORY##&quot;&gt;
        ///      &lt;xsl:variable name=&quot;dir-id&quot; select=&quot;generate-id(.)&quot;/&gt;
        ///      &lt;xsl:variable name=&quot;all-files&quot; select=&quot;count(.//##XML_ELEMENT_FILE##)&quot;/&gt;
        ///      &lt;xsl:variable name=&quot;all-dirs&quot; select=&quot;count(.//##XML_ELEMENT_DIRECTORY##)&quot;/&gt;
        ///      &lt;tr class=&quot;row&quot;&gt;
        ///        &lt;td class=&quot;content&quot; title=&quot;Direc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiffReportXslt {
            get {
                return ResourceManager.GetString("DiffReportXslt", resourceCulture);
            }
        }
    }
}
